name: CD

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Application.yml from Secret
        run: |
          echo ${{ secrets.APPLICATION_YML }} > src/main/resources/application.yml

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: List JAR files
        run: ls build/libs

      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_USER_TOKEN }}
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t ${{ secrets.DOCKER_USER_NAME }}/leets-blog-be:latest --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SECRET_HOST }}
          username: ${{ secrets.SSH_SECRET_USER }}
          port: 22
          key: ${{ secrets.SSH_SECRET_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USER_NAME }}/leets-blog-be:latest
            
            sudo docker compose up -d --no-deps leets-blog-be 
            
            echo "** 사용하지 않는 Docker 이미지 정리"
            sudo docker image prune -f